sudo: false
dist: trusty
language: rust
os:
  - linux
  - osx
rust:
- stable
- beta
- nightly
env:
  global:
    - WLA_DX_COMMIT="0aa6fda0d99c2acb54eeebc296a671caf040d7f6"

matrix:
  allow_failures:
  - rust: nightly

addons:
  apt:
    packages:
      cmake
      libsdl2-dev

cache:
  cargo: true
  directories:
    - $HOME/bin

before_install:
- openssl aes-256-cbc -K $encrypted_f29b02af6b5b_key -iv $encrypted_f29b02af6b5b_iv -in .travis/boot_roms.tar.enc -out .travis/boot_roms.tar -d
- tar xvf .travis/boot_roms.tar
- .travis/install_wla-dx.sh
- export PATH=$PATH:$HOME/bin
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

script:
- cargo build --verbose
- make -C tests clean all
- cargo test --all --verbose
