sudo: false
language: rust
rust:
- stable
- beta
- nightly
cache:
  cargo: true
matrix:
  allow_failures:
  - rust: nightly
env:
  global:
  - LIBRARY_PATH: "$HOME/sdl2/lib"
  - LD_LIBRARY_PATH: "$HOME/sdl2/lib"
before_install:
- openssl aes-256-cbc -K $encrypted_f29b02af6b5b_key -iv $encrypted_f29b02af6b5b_iv -in .travis/boot_roms.tar.enc -out .travis/boot_roms.tar -d
- tar xvf .travis/boot_roms.tar
- mkdir $HOME/bin && cd $HOME/bin
- curl -sSLO https://gekkio.fi/files/mooneye-gb/travis-precise64/SDL2-2.0.4-precise64.tar.bz2
- curl -sSLO https://gekkio.fi/files/mooneye-gb/travis-precise64/wlalink
- curl -sSLO https://gekkio.fi/files/mooneye-gb/travis-precise64/wla-gb
- md5sum -c $TRAVIS_BUILD_DIR/.travis/MD5SUMS && chmod +x wlalink && chmod +x wla-gb
- mkdir $HOME/sdl2 && cd $HOME/sdl2 && tar xjf $HOME/bin/SDL2-2.0.4-precise64.tar.bz2
- cd $TRAVIS_BUILD_DIR
script:
- cargo build --verbose
- cargo test --verbose
- "./run_acceptance_tests.sh"
