sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  cargo: true
  directories:
    - SDL2-2.0.4
    - wla-dx
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - LIBRARY_PATH: $HOME/sdl2/lib
    - LD_LIBRARY_PATH: $HOME/sdl2/lib
before_install:
  - curl -sSL http://www.libsdl.org/release/SDL2-2.0.4.tar.gz | tar xz
  - cd SDL2-2.0.4 && ./configure --prefix=$HOME/sdl2 && make && make install
  - mkdir -p wla-dx && curl -sSL https://github.com/vhelin/wla-dx/archive/f4ce81415d678cb05088fc537f582539b1fd4b47.tar.gz | tar xz -C wla-dx --strip-components=1
  - cd wla-dx && cmake . && make
