sudo: false
dist: trusty
language: rust
rust:
- stable
- beta
- nightly
addons:
  apt:
    packages:
      libsdl2-dev
cache:
  cargo: true
matrix:
  allow_failures:
  - rust: nightly
before_install:
- openssl aes-256-cbc -K $encrypted_f29b02af6b5b_key -iv $encrypted_f29b02af6b5b_iv -in .travis/boot_roms.tar.enc -out .travis/boot_roms.tar -d
- tar xvf .travis/boot_roms.tar
- curl -sSLO https://gekkio.fi/files/mooneye-gb/travis-precise64/wlalink
- curl -sSLO https://gekkio.fi/files/mooneye-gb/travis-precise64/wla-gb
- md5sum -c $TRAVIS_BUILD_DIR/.travis/MD5SUMS && chmod +x wlalink && chmod +x wla-gb
- cd $TRAVIS_BUILD_DIR
script:
- cargo build --verbose
- cargo test --verbose
- "./run_acceptance_tests.sh"
- cargo build --verbose
- make -C tests clean all
