sudo: false
dist: trusty
language: rust
rust:
- stable
- beta
- nightly
env:
  global:
    - WLA_DX_COMMIT="d1dcfd6142a71702471580e6ddca24652a63d00f"

matrix:
  allow_failures:
  - rust: nightly

addons:
  apt:
    packages:
      cmake
      libsdl2-dev

cache:
  cargo: true

before_install:
- openssl aes-256-cbc -K $encrypted_f29b02af6b5b_key -iv $encrypted_f29b02af6b5b_iv -in .travis/boot_roms.tar.enc -out .travis/boot_roms.tar -d
- tar xvf .travis/boot_roms.tar
- .travis/install_wla-dx.sh
- export PATH=$PATH:$HOME/bin

script:
- cargo build --verbose
- cargo test --verbose
- ./run_acceptance_tests.sh
- cargo build --verbose
- make -C tests clean all
