sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  cargo: true
  directories:
    - SDL2-2.0.4
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - LIBRARY_PATH: $HOME/sdl2/lib
    - LD_LIBRARY_PATH: $HOME/sdl2/lib
before_install:
  - curl -sSL http://www.libsdl.org/release/SDL2-2.0.4.tar.gz | tar xz
  - cd SDL2-2.0.4 && ./configure --prefix=$HOME/sdl2 && make && make install
  - mkdir $HOME/bin
  - cd $HOME/bin
  - curl -sSLO https://gekkio.fi/files/mooneye-gb/travis-precise64/wlalink
  - curl -sSLO https://gekkio.fi/files/mooneye-gb/travis-precise64/wla-gb
  - md5sum -c $TRAVIS_BUILD_DIR/.travis/MD5SUMS
  - cd $TRAVIS_BUILD_DIR
script:
  - cargo build --verbose
  - cargo test --verbose
  - ./run_acceptance_tests.sh
