[package]

name = "mooneye-gb"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
license = "GPL-3.0+"

[features]
acceptance_tests = []

[dependencies]
bitflags = "0.3"
crc = "1.2"
docopt = "0.6"
glium_sdl2 = "0.5"
nalgebra = "0.2"
num = "0.1"
podio = "0.1"
rustc-serialize = "0.3"
sdl2 = "0.7"
time = "0.1"

[dependencies.glium]
version = "0.8"
features = ["nalgebra"]
default-features = false

[dependencies.imgui]
version = "0.0.1"
features = ["glium", "sdl2"]

[dev-dependencies]
quickcheck = "0.2"
