[workspace]
members = ["core"]

[package]
name = "mooneye-gb"
version = "0.2.0-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
license = "GPL-3.0+"

[dependencies]
arraydeque = "0.4"
docopt = "1.0"
failure = "0.1"
glium = "0.22"
imgui = "0.0.21"
imgui-glium-renderer = "0.0.21"
log = "0.4"
mooneye-gb-core = { version = "0.2.0-pre", path = "core" }
nalgebra = "0.16"
num-traits = "0.2"
serde = "1.0"
serde_derive = "1.0"
sdl2 = "0.31"
simplelog = "0.5"

[dev-dependencies]
criterion = "0.2"

[profile.test]
opt-level = 2

[features]
include-bootroms = ["mooneye-gb-core/include-bootroms"]
