[package]

name = "mooneye-gb"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]

[dependencies.sdl2]
git = "https://github.com/Gekkio/rust-sdl2.git"
branch = "macro-semicolons"

[dependencies.snooze-rs]
git = "https://github.com/Gekkio/snooze-rs.git"

[dependencies.time]
git = "https://github.com/rust-lang/time.git"
