[package]

name = "mooneye-gb"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]

[features]
acceptance_tests = []

[dependencies]
bitflags = "*"
clock_ticks = "*"
getopts = "*"
num = "*"
sdl2 = "*"

[dependencies.snooze-rs]
git = "https://github.com/Gekkio/snooze-rs.git"

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
