[package]

name = "mooneye-gb"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]

[features]
acceptance_tests = []

[dependencies]
bitflags = "*"
clock_ticks = "*"
getopts = "*"
num = "*"
sdl2 = "*"
snooze-rs = "*"

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
