[package]

name = "mooneye-gb"
version = "0.0.0"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
license = "GPL-3.0+"

[features]
acceptance_tests = []

[dependencies]
bitflags = "*"
getopts = "*"
glium_sdl2 = "0.5"
nalgebra = "*"
num = "*"
podio = "*"
sdl2 = "0.7"
time = "*"

[dependencies.glium]
version = "0.8"
features = ["nalgebra"]
default-features = false

[dev-dependencies]
quickcheck = "*"
