[package]

name = "mooneye-gb"
version = "0.2.0-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
license = "GPL-3.0+"

[features]
acceptance_tests = []

[dependencies]
app_dirs = { git = "https://github.com/Gekkio/app-dirs-rs.git", branch = "mooneye-gb" }
bitflags = "1.0"
crc = "1.3"
docopt = "0.8"
error-chain = "0.11"
glium_sdl2 = { git = "https://github.com/Gekkio/glium-sdl2.git", branch = "glium0.19-sdl0.31" }
imgui = "0.0.18"
imgui-glium-renderer = "0.0.18"
log = "0.4"
nalgebra = "0.14"
num-traits = "0.2"
serde = "1.0"
serde_derive = "1.0"
sdl2 = "0.31"
simplelog = "0.5"
url = "1.7"

[dependencies.glium]
version = "0.19"
default-features = false

[dev-dependencies]
quickcheck = "0.6"
