[package]

name = "mooneye-gb"
version = "0.2.0-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
license = "GPL-3.0+"

[features]
acceptance_tests = []

[dependencies]
app_dirs = "1.1"
bitflags = "0.9"
crc = "1.3"
docopt = "0.8"
glium_sdl2 = "0.13"
log = "0.3"
nalgebra = "0.11"
num-traits = "0.1"
podio = "0.1"
serde = "1.0"
serde_derive = "1.0"
sdl2 = "0.27"
simplelog = "0.4"
url = "1.5"

[dependencies.glium]
version = "0.15"
default-features = false

[dependencies.imgui]
version = "0.0.10"
features = ["glium"]

[dev-dependencies]
quickcheck = "0.4"
