[workspace]
members = ["core"]

[package]
name = "mooneye-gb"
version = "0.2.0-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
license = "GPL-3.0+"

[dependencies]
docopt = "1.0"
failure = "0.1"
glium_sdl2 = { git = "https://github.com/Gekkio/glium-sdl2.git", branch = "glium0.19-sdl0.31" }
imgui = "0.0.18"
imgui-glium-renderer = "0.0.18"
log = "0.4"
mooneye-gb-core = { version = "0.2.0-pre", path = "core" }
nalgebra = "0.15"
num-traits = "0.2"
serde = "1.0"
serde_derive = "1.0"
sdl2 = "0.31"
simplelog = "0.5"
url = "1.7"

[dependencies.glium]
version = "0.19"
default-features = false

[profile.test]
opt-level = 1

[features]
include-bootroms = ["mooneye-gb-core/include-bootroms"]
