[package]

name = "mooneye-gb"
version = "0.2.0-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
license = "GPL-3.0+"

[features]
acceptance_tests = []

[dependencies]
app_dirs = "1.1"
bitflags = "0.9"
crc = "1.3"
docopt = "0.8"
glium_sdl2 = { git = "https://github.com/Gekkio/glium-sdl2.git", branch = "glium0.16-sdl0.30" }
imgui = "0.0.13"
imgui-glium-renderer = "0.0.13"
log = "0.3"
nalgebra = "0.12"
num-traits = "0.1"
podio = "0.1"
serde = "1.0"
serde_derive = "1.0"
sdl2 = "0.30"
simplelog = "0.4"
url = "1.5"

[dependencies.glium]
version = "0.16"
default-features = false

[dev-dependencies]
quickcheck = "0.4"
